package com.example.lichamviet.theme

import androidx.compose.ui.graphics.Color

// 1. Material 3 Modern Indigo / Ocean Blue (Mặc định)
val M3BluePrimary = Color(0xFF0B57D0)
val M3BlueOnPrimary = Color(0xFFFFFFFF)
val M3BluePrimaryContainer = Color(0xFFD3E3FD)
val M3BlueOnPrimaryContainer = Color(0xFF041E49)
val M3BlueSecondary = Color(0xFF00639B)
val M3BlueOnSecondary = Color(0xFFFFFFFF)
val M3BlueSecondaryContainer = Color(0xFFC2E7FF)
val M3BlueOnSecondaryContainer = Color(0xFF001D32)
val M3BlueTertiary = Color(0xFF006C4C)
val M3BlueOnTertiary = Color(0xFFFFFFFF)
val M3BlueTertiaryContainer = Color(0xFF89F8C7)
val M3BlueOnTertiaryContainer = Color(0xFF002114)

// 2. Material 3 Jade Green (Xanh Ngọc Bích)
val JadePrimary = Color(0xFF006C4C)
val JadeOnPrimary = Color(0xFFFFFFFF)
val JadePrimaryContainer = Color(0xFF89F8C7)
val JadeOnPrimaryContainer = Color(0xFF002114)
val JadeSecondary = Color(0xFF4C6357)
val JadeSecondaryContainer = Color(0xFFCEE9D9)
val JadeOnSecondaryContainer = Color(0xFF092016)

// 3. Material 3 Amber Warm (Vàng Hổ Phách)
val AmberPrimary = Color(0xFF855300)
val AmberOnPrimary = Color(0xFFFFFFFF)
val AmberPrimaryContainer = Color(0xFFFFDDB3)
val AmberOnPrimaryContainer = Color(0xFF2B1700)
val AmberSecondary = Color(0xFF705B40)
val AmberSecondaryContainer = Color(0xFFFBE0BD)
val AmberOnSecondaryContainer = Color(0xFF281805)

// 4. Material 3 Dark Sleek (Tối Trầm Hiện Đại)
val DarkPrimary = Color(0xFFA8C7FA)
val DarkOnPrimary = Color(0xFF062E6F)
val DarkPrimaryContainer = Color(0xFF0842A0)
val DarkOnPrimaryContainer = Color(0xFFD3E3FD)
val DarkSecondary = Color(0xFF7FCFFF)
val DarkOnSecondary = Color(0xFF003453)
val DarkSecondaryContainer = Color(0xFF004B76)
val DarkOnSecondaryContainer = Color(0xFFC2E7FF)
val DarkBg = Color(0xFF111318)
val DarkSurface = Color(0xFF111318)
val DarkSurfaceContainer = Color(0xFF1D2024)
val DarkSurfaceContainerHigh = Color(0xFF282A2F)
val DarkOnSurface = Color(0xFFE2E2E9)
val DarkOnSurfaceVariant = Color(0xFFC4C7D0)
val DarkOutline = Color(0xFF8E9099)
val DarkOutlineVariant = Color(0xFF44474E)

// Màu chức năng lịch
val AuspiciousGreen = Color(0xFF006C4C)
val AuspiciousGreenContainer = Color(0xFFE8F5E9)
val SundayRed = Color(0xFFBA1A1A)
val SundayRedContainer = Color(0xFFFFDAD6)
val TermBlue = Color(0xFF0277BD)
val TermBlueContainer = Color(0xFFE1F5FE)

// Light Neutrals
val NeutralSurface = Color(0xFFFDFBFF)
val NeutralSurfaceContainer = Color(0xFFF0F4F9)
val NeutralSurfaceContainerHigh = Color(0xFFE9EEF6)
val NeutralSurfaceContainerLow = Color(0xFFF7F9FC)
val NeutralOnSurface = Color(0xFF1A1C1E)
val NeutralOnSurfaceVariant = Color(0xFF44474E)
val NeutralOutline = Color(0xFF74777F)
val NeutralOutlineVariant = Color(0xFFC4C7D0)
